-- SQL CREATE TABLE BRRANDS
CREATE TABLE public.brands (
	id int8 NOT NULL,
	description varchar(50) NOT NULL,
	CONSTRAINT pk_brands PRIMARY KEY (id),
	CONSTRAINT uk_brands_description UNIQUE (description)
);
-- SQL CREATE TABLE CATEGORIES
CREATE TABLE public.categories (
	id int8 NOT NULL,
	description varchar(50) NOT NULL,
	CONSTRAINT pk_categories PRIMARY KEY (id),
	CONSTRAINT uk_categories_description UNIQUE (description)
);

-- SQL CREATE TABLE PRODUCTS
CREATE TABLE public.product (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	click_count int4 NOT NULL,
	"depth" float8 NOT NULL,
	description varchar(2000) NULL,
	height float8 NOT NULL,
	"name" varchar(100) NULL,
	price numeric(10, 2) NOT NULL,
	stock_alert_enabled bool NULL,
	stock_alert_quantity int4 NULL,
	stock_quantity int4 NOT NULL,
	unit_type varchar(50) NULL,
	weight float8 NOT NULL,
	width float8 NOT NULL,
	youtube_link varchar(1000) NULL,
	brand_id int8 NOT NULL,
	category_id int8 NOT NULL,
	CONSTRAINT pk_product PRIMARY KEY (id),
	CONSTRAINT fk_brand FOREIGN KEY (brand_id) REFERENCES public.brands(id),
	CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES public.categories(id)
);