CREATE TABLE public.brand (
	id int8 NOT NULL,
	description varchar(50) NOT NULL,
	CONSTRAINT brand_description_uk UNIQUE (description),
	CONSTRAINT brand_pkey PRIMARY KEY (id)
);

CREATE TABLE public.category (
	id int8 NOT NULL,
	description varchar(50) NOT NULL,
	CONSTRAINT category_description_uk UNIQUE (description),
	CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE public.product (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	click_count int4 NULL,
	"depth" float8 NOT NULL,
	description text NULL,
	height float8 NOT NULL,
	"name" varchar(100) NOT NULL,
	price numeric(10, 2) NOT NULL,
	stock_alert_enabled bool NULL,
	stock_alert_quantity int4 NULL,
	stock_quantity int4 NOT NULL,
	unit_type varchar(50) NULL,
	weight float8 NOT NULL,
	width float8 NOT NULL,
	youtube_link varchar(1000) NULL,
	brand_id int8 NOT NULL,
	category_id int8 NOT NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT brand_fk FOREIGN KEY (brand_id) REFERENCES public.brand(id),
	CONSTRAINT category_fk FOREIGN KEY (category_id) REFERENCES public.category(id)
);

CREATE TABLE public.product_image (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	original_image text NOT NULL,
	thumbnail_image text NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT product_image_pkey PRIMARY KEY (id),
	CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES public.product(id)
);


CREATE TABLE public.discount_coupon (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(50) NOT NULL,
	discount_amount numeric(38, 2) NULL,
	due_date timestamp(6) NOT NULL,
	percentage numeric(38, 2) NULL,
	CONSTRAINT dc_code_uk UNIQUE (code),
	CONSTRAINT discount_coupon_pkey PRIMARY KEY (id)
);


CREATE TABLE public.payment_method (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	payment_type varchar(255) NOT NULL,
	CONSTRAINT payment_method_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'BANK_SLIP'::character varying, 'PIX'::character varying])::text[]))),
	CONSTRAINT payment_method_pkey PRIMARY KEY (id),
	CONSTRAINT payment_type_uk UNIQUE (payment_type)
);

CREATE TABLE public."role" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"role" varchar(255) NOT NULL,
	CONSTRAINT role_pkey PRIMARY KEY (id),
	CONSTRAINT role_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[]))),
	CONSTRAINT role_uk UNIQUE (role)
);

CREATE TABLE public.person (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	phone varchar(20) NOT NULL,
	CONSTRAINT email_uk UNIQUE (email),
	CONSTRAINT person_pkey PRIMARY KEY (id),
	CONSTRAINT phone_uk UNIQUE (phone)
);


CREATE TABLE public.person_fisica (
	cpf varchar(11) NOT NULL,
	date_of_birth date NOT NULL,
	id int8 NOT NULL,
	CONSTRAINT cpf_uk UNIQUE (cpf),
	CONSTRAINT person_fisica_pkey PRIMARY KEY (id),
	CONSTRAINT person_fisica_fk FOREIGN KEY (id) REFERENCES public.person(id)
);

CREATE TABLE public.person_juridica (
	category varchar(255) NULL,
	cnpj varchar(14) NOT NULL,
	corporate_name varchar(255) NOT NULL,
	municipal_registration varchar(255) NULL,
	state_registration varchar(255) NULL,
	trade_name varchar(255) NOT NULL,
	id int8 NOT NULL,
	CONSTRAINT cnpj_uk UNIQUE (cnpj),
	CONSTRAINT person_juridica_pkey PRIMARY KEY (id),
	CONSTRAINT person_juridica_fk FOREIGN KEY (id) REFERENCES public.person(id)
);

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(255) NOT NULL,
	password_updated_at date NOT NULL,
	username varchar(30) NOT NULL,
	person_id int8 NOT NULL,
	CONSTRAINT username_uk UNIQUE (username),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES public.person(id)
);


CREATE TABLE public.users_roles (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT role_user_uk UNIQUE (user_id, role_id),
	CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES public."role"(id),
	CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.address (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city varchar(255) NOT NULL,
	complement varchar(255) NULL,
	neighborhood varchar(255) NOT NULL,
	"number" varchar(255) NOT NULL,
	state varchar(255) NOT NULL,
	street varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	zip_code varchar(255) NOT NULL,
	person_id int8 NOT NULL,
	CONSTRAINT address_pkey PRIMARY KEY (id),
	CONSTRAINT address_type_check CHECK (((type)::text = ANY ((ARRAY['BILLING'::character varying, 'DELIVERY'::character varying])::text[]))),
	CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES public.person(id)
);

CREATE TABLE public.account_payable (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NOT NULL,
	discount_amount numeric(10, 2) NULL,
	due_date date NOT NULL,
	payment_date date NULL,
	status varchar(255) NOT NULL,
	total_amount numeric(10, 2) NOT NULL,
	address_id int8 NOT NULL,
	payment_method_id int8 NOT NULL,
	person_id int8 NOT NULL,
	supplier_id int8 NOT NULL,
	CONSTRAINT account_payable_pkey PRIMARY KEY (id),
	CONSTRAINT account_payable_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying, 'CANCELLED'::character varying, 'NEGOTIATED'::character varying, 'OPEN'::character varying, 'SETTLED'::character varying])::text[]))),
	CONSTRAINT address_fk FOREIGN KEY (address_id) REFERENCES public.address(id),
	CONSTRAINT payment_method_fk FOREIGN KEY (payment_method_id) REFERENCES public.payment_method(id),
	CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES public.person(id),
	CONSTRAINT supplier_fk FOREIGN KEY (supplier_id) REFERENCES public.person(id)
);

CREATE TABLE public.nota_fiscal_compra (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount_icms numeric(38, 2) NOT NULL,
	description varchar(255) NULL,
	discount_amount numeric(38, 2) NULL,
	"number" varchar(255) NOT NULL,
	purchase_date timestamp(6) NOT NULL,
	total_amount numeric(38, 2) NOT NULL,
	account_payable_id int8 NULL,
	person_id int8 NULL,
	CONSTRAINT nfc_account_payable_uk UNIQUE (account_payable_id),
	CONSTRAINT nfc_number_uk UNIQUE (number),
	CONSTRAINT nota_fiscal_compra_pkey PRIMARY KEY (id),
	CONSTRAINT account_payable_fk FOREIGN KEY (account_payable_id) REFERENCES public.account_payable(id),
	CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES public.person(id)
);

CREATE TABLE public.nota_item_product (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(38, 2) NOT NULL,
	quantity float8 NOT NULL,
	nota_fiscal_compra_id int8 NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT nota_item_product_pkey PRIMARY KEY (id),
	CONSTRAINT nota_fiscal_compra_fk FOREIGN KEY (nota_fiscal_compra_id) REFERENCES public.nota_fiscal_compra(id),
	CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES public.product(id)
);

CREATE TABLE public.sale_purchase (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	delivery_date date NOT NULL,
	delivery_days int4 NOT NULL,
	discount_amount numeric(38, 2) NULL,
	sale_date date NOT NULL,
	shipping_cost numeric(38, 2) NOT NULL,
	total_amount numeric(38, 2) NOT NULL,
	billing_address_id int8 NULL,
	delivery_address_id int8 NOT NULL,
	discount_coupon_id int8 NULL,
	payment_method_id int8 NOT NULL,
	person_id int8 NOT NULL,
	CONSTRAINT sale_purchase_pkey PRIMARY KEY (id),
	CONSTRAINT billing_address_fk FOREIGN KEY (billing_address_id) REFERENCES public.address(id),
	CONSTRAINT delivery_address_fk FOREIGN KEY (delivery_address_id) REFERENCES public.address(id),
	CONSTRAINT discount_coupon_fk FOREIGN KEY (discount_coupon_id) REFERENCES public.discount_coupon(id),
	CONSTRAINT payment_method_fk FOREIGN KEY (payment_method_id) REFERENCES public.payment_method(id),
	CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES public.person(id)
);


CREATE TABLE public.sale_item (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(38, 2) NOT NULL,
	quantity float8 NOT NULL,
	product_id int8 NOT NULL,
	sale_purchase_id int8 NOT NULL,
	CONSTRAINT sale_item_pkey PRIMARY KEY (id),
	CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES public.product(id),
	CONSTRAINT sale_purchase_fk FOREIGN KEY (sale_purchase_id) REFERENCES public.sale_purchase(id)
);

CREATE TABLE public.nota_fiscal_venda (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	pdf text NOT NULL,
	"xml" text NOT NULL,
	"number" varchar(255) NOT NULL,
	series varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	sale_purchase_id int8 NOT NULL,
	CONSTRAINT nfv_number_uk UNIQUE (number),
	CONSTRAINT nfv_sale_purchase_uk UNIQUE (sale_purchase_id),
	CONSTRAINT nota_fiscal_venda_pkey PRIMARY KEY (id),
	CONSTRAINT sale_purchase_fk FOREIGN KEY (sale_purchase_id) REFERENCES public.sale_purchase(id)
);

CREATE TABLE public.tracking_status (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city varchar(255) NOT NULL,
	distribution_center varchar(255) NOT NULL,
	state varchar(255) NOT NULL,
	status varchar(255) NOT NULL,
	sale_purchase_id int8 NULL,
	CONSTRAINT tracking_status_pkey PRIMARY KEY (id),
	CONSTRAINT ts_sale_purchase_uk UNIQUE (sale_purchase_id),
	CONSTRAINT sale_purchase_fk FOREIGN KEY (sale_purchase_id) REFERENCES public.sale_purchase(id)
);

CREATE TABLE public.account_receivable (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	discount_amount numeric(10, 2) NULL,
	due_date date NOT NULL,
	payment_date date NULL,
	status varchar(255) NOT NULL,
	total_amount numeric(10, 2) NOT NULL,
	person_id int8 NULL,
	sale_purchase_id int8 NULL,
	CONSTRAINT account_receivable_pkey PRIMARY KEY (id),
	CONSTRAINT account_receivable_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT ar_sale_purchase_uk UNIQUE (sale_purchase_id),
	CONSTRAINT person_fk FOREIGN KEY (person_id) REFERENCES public.person(id),
	CONSTRAINT sale_purchase_fk FOREIGN KEY (sale_purchase_id) REFERENCES public.sale_purchase(id)
);