CREATE TABLE users_verifier (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"token" varchar(255) NOT NULL,
	user_id int8 NOT NULL,
	expiration_date timestamp(6) NOT NULL,
	CONSTRAINT user_verifier_token_uk UNIQUE ("token"),
	CONSTRAINT users_verifier_pkey PRIMARY KEY (id),
	CONSTRAINT uv_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);
